### ISSUE TITLE
baseMVA error.

### ISSUE THREAD

**Issue by bukhsh** [bukhsh/oats#139]
The following error is reported when '1.0' is multiplied by baseMVA value. 

Traceback (most recent call last):
  File "/Users/wbukhsh/GitHub/oats/runtest.py", line 9, in <module>
    dcopf(neos=False,solver='glpk',tc= '/Users/wbukhsh/Downloads/23EC NOCON Base.xlsx')
  File "/Users/wbukhsh/GitHub/oats/oats/run.py", line 106, in dcopf
    runcase(testcase,model,opt)
  File "/Users/wbukhsh/GitHub/oats/oats/runcase.py", line 106, in runcase
    o.printoutputxls()
  File "/Users/wbukhsh/GitHub/oats/oats/printoutput.py", line 186, in printoutputxls
    'pG(MW)':round(self.instance.pG[g[1]].value*self.instance.baseMVA,3),\
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

the error goes away if instance.baseMVA is replaced by instance.baseMVA.value

needs further investigation as to what's causing this issue

**Comment by bukhsh** [comment]
this issue is fixed
